name: Release to prod
on:
  push:
    branches:
      - master-cere

jobs:
  build-and-deploy:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/build-and-upload-static.yaml@master
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      build_container: 'node:14-buster'
      deploy_container: 'ubuntu:20.04'
      install_packages_command: 'cp .env.prod .env; sh ./scripts/copy-prod-config.sh; yarn install'
      build_command: 'yarn build'
      path_to_static_files_to_upload: 'build'
    secrets:
      NETWORK_AWS_ACCESS_KEY_ID: ${{ secrets.PRD_NETWORK_AWS_ACCESS_KEY_ID }}
      NETWORK_AWS_SECRET_ACCESS_KEY: ${{ secrets.PRD_NETWORK_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_PRD }}
      CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID_PRD }}
